# Generated by Django 4.1.7 on 2024-05-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saharahco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_des',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='service_name',
            field=models.CharField(default='Default Service Name', max_length=35),
        ),
    ]
